<a href="index.html" class="logo"><img src="./images/PixelCat.png" alt="CashCats Logo">CashCats</a>

<input type="checkbox" id="menu-bar">
<label for="menu-bar" class="nav-icons">
    <i class="fa" id="menu-icon">&#xf0c9;</i>
    <i class="fa" id="close-icon">&#xf00d;</i>
</label>

<nav>
    <ul class="nav-list">
        <li><a href="index.html">Home</a></li>
        <li><a href="jobs.html">Jobs</a></li>
        <li><a href="about.html">About</a></li>
        <li><a href="enhancements.html">Enhancements</a></li>
        <li><a href="application.html" class="hidden">Apply Now</a></li>
    </ul>
</nav>

<a href="application.html" class="action-btn">Apply Now</a>